const MESSAGES = [
  'Small honest actions beat perfect plans.',
  'You are building proof, not just intention.',
  'Consistency grows quietly before it feels loud.',
  'Keep the promise in front of you, not all promises forever.',
  'One deliberate check-in can reset an entire week.',
  'Progress is often private first, obvious later.',
  'Today is enough to practice who you want to be.',
  'Momentum starts with a single marked square.',
  'The best way to build a habit is to show up, not to feel motivated.',
  'The point is to build consistency, not to be perfect.',
  'Small commitments are the building blocks of big change.',
  'Focus on the next right action, not the entire staircase.',
  'Consistency is built through repeated choices, not one-time decisions.',
  'The most important part of a commitment is the follow-through.',
  'You are proving what you believe about yourself with every choice.',
  'It\'s better to do something imperfectly than to do nothing perfectly.',
  'The habit of showing up is more important than the outcome of any single day.',
  'Consistency creates a foundation of trust with yourself.',
  'Every time you follow through, you are reinforcing a new identity.',
  'The journey of change is built on small wins, not giant leaps.'
];

const DAILY_PROMPTS = [
  'What commitment mattered most today?',
  'What almost pulled you off track, and what kept you grounded?',
  'What made today easier than yesterday?',
  'Where did you choose honesty over comfort?',
  'What is one tiny action tomorrow-you will be grateful for?',
  'What did you learn about your resistance today?',
  'If today had a theme, what was it?',
  'What standard are you quietly raising?',
  'What did you postpone today, and why?',
  'Where did you follow through even when motivation was low?',
  'What boundary protected your focus today?',
  'What was one moment you felt fully present?',
  'What did you avoid that deserves a 10-minute start tomorrow?',
  'Which choice today matched your long-term self best?',
  'What friction point should you redesign for tomorrow?',
  'What helped your energy most today?',
  'What would make tomorrow 5% better?',
  'What did you learn from a miss or mistake today?',
  'What is one promise you will keep before noon tomorrow?',
  'What are you proud of that no one else saw?',
  'What task is still mentally open, and what is the next step?',
  'If you repeated today for a month, where would you end up?',
  'What can you simplify tomorrow to reduce resistance?'
];

const GOAL_IDEAS = {
  work: [
    'Identify 1-3 critical tasks that truly move the needle',
    'Identify what I can delegate, automate, or eliminate to focus on the critical tasks',
    'Do one thing to move a project forward',
    'Spend {minutes} minutes on business development',
    'Write one email to a potential client or collaborator',
    'Post one piece of content related to my work',
    'Do one thing to improve my website or portfolio',
    'Spend {minutes} minutes learning a new skill related to my work',
    'Review and update one aspect of my business strategy',
    'Do one thing to nurture an important professional relationship',
    'Write down one insight from something I learned recently in my field',
    'Try one new technique or approach in my work',
    'Spend {minutes} minutes learning about a topic outside my field that could inspire new ideas in my work',
    'Write down one question I have about something I want to learn related to my work',
    'Do one thing to improve my work environment or setup',
    'Spend {minutes} minutes on a project I\'ve been procrastinating related to my work',
    'Write down one thing I appreciate about my work or progress recently',
    'Do one thing to celebrate a recent win or milestone in my work',
    'Write down one thing I am looking forward to in my work and why',
    'Do one thing to connect with someone in my industry or field',
    'Spend {minutes} minutes reflecting on my long-term goals and vision for my work'
  ],
  finances: [
    'Review and update my budget for {minutes} minutes',
    'Track all my expenses for the day',
    'Do a {minutes}-minute financial declutter (cancel unused subscriptions, delete old payment methods, etc.)',
    'Spend {minutes} minutes learning about a personal finance topic I\'m less familiar with',
    'Write down one financial goal I have and a next step to work towards it',
    'Review my recent purchases and identify one area to cut back on',
    'Do one thing to increase my income (apply for a new job, reach out to a potential client, etc.)',
    'Do one thing to save money (cook at home instead of eating out, find a cheaper alternative for something I regularly buy, etc.)',
    'Write down one thing I appreciate about my current financial situation or progress recently',
    'Do one thing to celebrate a recent financial win or milestone',
    'Write down one thing I am looking forward to in my financial future and why',
    'Spend {minutes} minutes reflecting on my relationship with money and how it aligns with my values',
    'Do one thing to connect with someone about finances (talk to a financial advisor, discuss money goals with a partner, etc.)',
    'Write down one question I have about something I want to learn related to personal finance',
    'Do one thing to improve my financial organization or tracking system',
    'Spend {minutes} minutes on a financial task I\'ve been procrastinating (reconciling accounts, applying for a credit card, etc.)',
    'Write down one thing I appreciate about my financial habits or progress recently',
    'Do one thing to celebrate a recent win or milestone in my financial journey',
    'Write down one thing I am looking forward to in my financial future and why'
  ],
  health: [
    'Walk {minutes} minutes outside',
    'Do a {minutes}-minute bodyweight workout',
    'Sleep plan: in bed before 11:00 PM',
    'Stretch for {minutes} minutes',
    'Drink water before coffee',
    'No phone first {minutes} minutes after waking',
    'No screens 30 minutes before bed',
    'Stand up and move for 3 minutes every hour',
    'Try one new healthy recipe this week',
    'Take a short walk after each meal',
    'Do one thing to improve sleep environment',
    'Limit caffeine to before 2:00 PM',
    'Have a technology sunset starting at 8:00 PM',
    'Go to bed with a clear mind',
    'Have a device-free morning routine',
    'Get outdoors during daylight hours',
    'Get at least 7 hours of sleep on at least 5 nights this week',
    'Do not smoke or vape today',
    'Do not drink alcohol today',
    'Eat a healthy breakfast'
  ],
  mind: [
    'Meditate for {minutes} minutes',
    'Journal for {minutes} minutes',
    'Read one chapter before bed',
    'Take a {minutes}-minute no-screen reset',
    'Write 3 things I am grateful for',
    'Do 10 minutes of breathwork',
    'Write down one thing I am avoiding and a next step to address it',
    'Spend {minutes} minutes on a hobby I enjoy',
    'Write down one thing I am looking forward to and why',
    'Do one thing that brings me joy',
    'Write down one positive thing about my day',
    'Spend {minutes} minutes in nature',
    'Listen to one song that lifts my mood',
    'Do one creative activity for {minutes} minutes',
    'Write down one thing I appreciate about myself',
    'Take a mindful break and notice 5 things around me',
    'Write down one thing I accomplished today, no matter how small'
  ],
  learning: [
    'Study a skill for {minutes} minutes',
    'Practice coding for {minutes} minutes',
    'Review notes for {minutes} minutes',
    'Watch one lesson and summarize it',
    'Learn 10 new words',
    'Build one tiny project step',
    'Read one article in my field',
    'Listen to one educational podcast episode',
    'Write one reflection on what I learned recently',
    'Teach one concept I recently learned to someone else',
    'Do one practice problem in a subject I want to improve',
    'Review one mistake and identify a next step to improve',
    'Spend {minutes} minutes on deliberate practice',
    'Read one chapter of a non-fiction book',
    'Write down one insight from something I learned recently',
    'Try one new technique or approach in my work',
    'Spend {minutes} minutes learning about a topic outside my field',
    'Write down one question I have about something I want to learn'
  ],
  relationships: [
    'Have at least one social interaction today',
    'Send one thoughtful message',
    'Call family for {minutes} minutes',
    'Have one device-free meal with someone',
    'Give one sincere compliment',
    'Ask one better question today',
    'Check in with one friend',
    'Have a 10-minute phone or video call with a friend or family member',
    'Do one kind thing for someone else',
    'Express appreciation to someone who helped you recently',
    'Have a 15-minute in-person conversation with someone',
    'Spend quality time with a pet',
    'Write a handwritten note to someone',
    'Reconnect with someone you haven\'t talked to in a while',
    'Have a meaningful conversation with a colleague',
    'Do one activity with a friend or family member',
    'Share one positive thing about your day with someone else',
    'Ask someone about their day and listen attentively',
    'Do one thing to nurture an important relationship',
    'Spend {minutes} minutes on a video call with a friend or family member'
  ],
  organization: [
    'Tidy one area for {minutes} minutes',
    'Plan top 3 priorities for tomorrow',
    'Inbox zero sprint for {minutes} minutes',
    'Review budget for {minutes} minutes',
    'Prep tomorrow clothes and workspace',
    'Delete 20 unnecessary files/emails',
    'Organize one area for {minutes} minutes',
    'Do a {minutes}-minute digital declutter',
    'Make a meal plan for the week',
    'Do a {minutes}-minute tidy-up before bed',
    'Write a to-do list for tomorrow',
    'Set calendar reminders for important tasks/events',
    'Review and update one recurring task or subscription',
    'Spend {minutes} minutes on a project I\'ve been procrastinating',
    'Clean up one area of your home',
    'Organize one area of your home',
    'Do a {minutes}-minute tidy-up of your digital files',
    'Review and update your budget or finances',
    'Plan your schedule for the next day',
    'Set up a new system to stay organized'
  ]
};

globalThis.MESSAGES = MESSAGES;
globalThis.DAILY_PROMPTS = DAILY_PROMPTS;
globalThis.GOAL_IDEAS = GOAL_IDEAS;
